# Generated by Django 4.2.6 on 2023-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, default=80.20294967040904, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
