# Generated by Django 4.2.6 on 2023-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_books_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=36.89665591630063, max_digits=6),
        ),
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
