# Generated by Django 4.2.6 on 2023-10-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_books_price_alter_books_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=89.06797971162732, max_digits=6),
        ),
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
